#!/bin/bash
function is_vbox_installed() {
  if [[ "$(type -t VBoxManage)" ]]; then
    return 0
  else
    return 1
  fi
}

function vbox_vm_list() {
  vbox_vm_list=$(VBoxManage list vms)
  echo $vbox_vm_list
}

function start_vm_headless() {
  vbox_vm_headless_start=$(VBoxManage startvm $1 --type headless)
  echo $vbox_vm_list
}

if is_vbox_installed $1; then
  if [ "$1" != "" ]; then
    vm_name=$1
    if [[ `vbox_vm_list` == *$vm_name* ]]; then
      echo `start_vm_headless $vm_name`
    else
      echo "VM $vm_name is not available in list!"
    fi
  else
    echo "Please enter a VM name as param!"
  fi
else
  echo "VirtualBox is currently not installed on your system or VBoxManage command does not work correctly!"
fi
exit
